Fix compatibility with Python 3.9
This fixes error like the following when running xctestrunner using
Python 3.9:

```
AttributeError: module 'plistlib' has no attribute 'readPlist'
```

`plistlib.readPlist` and `plistlib.writePlist` are no longer available
since Python 3.9, and their replacements are available since Python
3.4. This change replaces them with wrapper functions to make
xctestrunner compatible with a multiple Python versions.